version: "3.9"

networks:
  backend:

volumes: 
  simple_bank_data:

services:
  postgres:
    image: postgres:14.5-alpine3.16
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - simple_bank_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}